// Silicon-Optimised Code Generation — generates runnable Python for CPU, GPU,
// and neuromorphic targets from an AMISGC experiment configuration.
//
// Architecture note (Replit free tier): pure string template generation.
// No execution of generated code happens on the Replit server. The output is
// a Python file the researcher downloads and runs on their own hardware.
// GPU target uses PyTorch (CUDA); neuromorphic target uses Norse (PyTorch-based
// spiking neural network library for Loihi-compatible workflows).

export type CodeTarget = "cpu" | "gpu" | "neuromorphic";

export interface CodeGenConfig {
  target: CodeTarget;
  params: Record<string, number | boolean | string>;
  scale: 81 | 810 | 81000;
  ticksPerCombo?: number;
  experimentLabel?: string;
}

export interface CodeGenResult {
  target: CodeTarget;
  filename: string;
  language: string;
  code: string;
  runInstructions: string;
  estimatedSpeedup: string;
}

// ── Template helpers ───────────────────────────────────────────────────────────

function paramBlock(params: Record<string, number | boolean | string>): string {
  return Object.entries(params)
    .map(([k, v]) => `    ${k} = ${JSON.stringify(v)}`)
    .join("\n");
}

function header(label: string, target: CodeTarget): string {
  const targetLabel = { cpu: "CPU (NumPy)", gpu: "GPU (PyTorch CUDA)", neuromorphic: "Neuromorphic (Norse/Loihi)" }[target];
  return `# AMISGC Generated Code — ${label}
# Target: ${targetLabel}
# Generated by AMISGC Research Platform v13.0
#
# Science goal: test emergent specialisation in a general-purpose neural field.
# Efficiency tools (this file) are used to scale experiments — not as an end goal.
#
# Core metrics: Phi (global integration), PU (predictive utility), S_C (stability)
# Gate I: Phi > 0.05 AND PU > 0.1 AND S_C > 0.1 sustained >= 1000 ticks

`;
}

// ── CPU template (NumPy) ───────────────────────────────────────────────────────

function generateCPU(cfg: CodeGenConfig): string {
  const { params, scale, ticksPerCombo = 30000, experimentLabel = "amisgc-experiment" } = cfg;
  return header(experimentLabel, "cpu") + `import numpy as np
from dataclasses import dataclass, field
from typing import Optional
import json, time, sys

# ── Hyperparameters ────────────────────────────────────────────────────────────
@dataclass
class Config:
    N: int = ${scale}
    ticks: int = ${ticksPerCombo}
${paramBlock(params)}
    # Existence Gate thresholds
    PHI_MIN: float = 0.05
    PU_MIN: float = 0.10
    SC_MIN: float = 0.10
    GATE_STREAK_TARGET: int = 1000
    seed: Optional[int] = None

cfg = Config()
rng = np.random.default_rng(cfg.seed)

# ── Network state ──────────────────────────────────────────────────────────────
N = cfg.N
a = rng.random(N).astype(np.float32)          # attention logits
y = np.zeros(N, dtype=np.float32)             # activity
h = np.ones(N, dtype=np.float32) * 0.5        # membrane potential
atp = np.ones(N, dtype=np.float32)            # metabolic energy (ATP)
a_slow = a.copy()                              # slow apical EMA
W = rng.normal(0, 1.0 / np.sqrt(N), (N, N)).astype(np.float32)
np.fill_diagonal(W, 0)

# ── Metrics accumulators ───────────────────────────────────────────────────────
gate_streak = 0
gate_ever_opened = False
phi_history = []
pu_history = []
sc_history = []

def softmax(x):
    e = np.exp(x - x.max())
    return e / e.sum()

def compute_phi(y, W, n_samples=20):
    """Approximated integrated information using pairwise mutual information."""
    if y.sum() < 1e-8:
        return 0.0
    active = np.where(y > 0.05)[0]
    if len(active) < 2:
        return 0.0
    idx = active[rng.choice(len(active), min(n_samples, len(active)), replace=False)]
    mi_sum = 0.0
    for i in range(len(idx)):
        for j in range(i + 1, len(idx)):
            xi, xj = y[idx[i]], y[idx[j]]
            mi_sum += abs(xi - xj) * 0.5
    n = len(idx) * (len(idx) - 1) / 2
    return float(mi_sum / max(n, 1))

def compute_pu(y, a_slow):
    """Predictive Utility: correlation between prediction (a_slow) and outcome (y)."""
    if y.std() < 1e-8 or a_slow.std() < 1e-8:
        return 0.0
    return float(np.corrcoef(y, a_slow)[0, 1])

def compute_sc(y_now, y_prev):
    """Stability Coherence: cosine similarity between consecutive activity states."""
    n1 = np.linalg.norm(y_now)
    n2 = np.linalg.norm(y_prev)
    if n1 < 1e-8 or n2 < 1e-8:
        return 0.0
    return float(np.dot(y_now, y_prev) / (n1 * n2))

# ── Main simulation loop ───────────────────────────────────────────────────────
y_prev = y.copy()
t_start = time.time()

print(f"AMISGC CPU run | N={N} | ticks={cfg.ticks}")
_report_keys = ['TAU_ATT', 'GAMMA_GLOBAL', 'BETA_ENTROPY', 'DELTA_TEMPORAL', 'NOISE_SIGMA', 'FIRE_COST', 'REGEN', 'COOP_BONUS']
print(f"Parameters: {dict((k, getattr(cfg, k)) for k in _report_keys if hasattr(cfg, k))}")

for t in range(cfg.ticks):
    # 1. Global field G (coherence-amplifying formula)
    C = softmax(a)
    G_num = np.sum(C * a ** 2)
    G_den = np.sum(C * a) + 1e-8
    G = float(np.clip(G_num / G_den, -4, 4))

    # 2. Attention softmax with global field injection
    tau = float(getattr(cfg, 'TAU_ATT', 1.0))
    gamma = float(getattr(cfg, 'GAMMA_GLOBAL', 2.0))
    beta = float(getattr(cfg, 'BETA_ENTROPY', 0.3))
    delta = float(getattr(cfg, 'DELTA_TEMPORAL', 0.4))
    sigma = float(getattr(cfg, 'NOISE_SIGMA', 0.02))

    logits = (a + gamma * G) / tau
    C = softmax(logits)

    # 3. Neuron update (predictive coding: somatic potential driven by attention + lateral)
    lateral = W @ y
    h_new = (1 - delta) * h + delta * (C + gamma * G + lateral)
    noise = rng.normal(0, sigma, N).astype(np.float32)
    y_new = np.maximum(0, h_new + noise)

    # 4. Entropy gradient reward (broad participation pressure)
    entropy = -np.sum(C * np.log(C + 1e-8))
    H_max = np.log(N)
    entropy_bonus = beta * (entropy / (H_max + 1e-8))
    a = a + 0.01 * (C - a) + entropy_bonus * 0.01

    # 5. Slow apical EMA
    a_slow = 0.98 * a_slow + 0.02 * a

    # 6. ATP (metabolic gating) — FIRE_COST controls metabolic cost per spike
    fire_cost = float(getattr(cfg, 'FIRE_COST', 4.0)) / 100.0
    regen = float(getattr(cfg, 'REGEN', 1.1)) / 100.0
    atp = np.clip(atp - fire_cost * y_new + regen, 0.1, 1.0)

    y_prev_copy = y.copy()
    h = h_new
    y = y_new

    # 7. Compute metrics every 100 ticks
    if t % 100 == 0:
        phi = compute_phi(y, W)
        pu = max(0.0, compute_pu(y, a_slow))
        sc = max(0.0, compute_sc(y, y_prev_copy))
        phi_history.append(phi)
        pu_history.append(pu)
        sc_history.append(sc)

        # Existence Gate check
        gate_open = phi > cfg.PHI_MIN and pu > cfg.PU_MIN and sc > cfg.SC_MIN
        if gate_open:
            gate_streak += 100
            if gate_streak >= cfg.GATE_STREAK_TARGET:
                gate_ever_opened = True
        else:
            gate_streak = 0

        if t % 5000 == 0:
            elapsed = time.time() - t_start
            status = "GATE OPEN" if gate_ever_opened else f"NO-GO (streak={gate_streak})"
            print(f"  t={t:6d} | Phi={phi:.4f} | PU={pu:.4f} | S_C={sc:.4f} | {status} | {elapsed:.1f}s")

# ── Results ────────────────────────────────────────────────────────────────────
elapsed = time.time() - t_start
result = {
    "gate_opened": gate_ever_opened,
    "gate_streak_max": gate_streak,
    "final_phi": phi_history[-1] if phi_history else 0,
    "final_pu": pu_history[-1] if pu_history else 0,
    "final_sc": sc_history[-1] if sc_history else 0,
    "mean_phi": float(np.mean(phi_history)) if phi_history else 0,
    "elapsed_s": elapsed,
    "ticks_per_sec": cfg.ticks / elapsed,
}
print("\\n=== RESULT ===")
print(json.dumps(result, indent=2))
sys.exit(0 if gate_ever_opened else 1)
`;
}

// ── GPU template (PyTorch CUDA) ────────────────────────────────────────────────

function generateGPU(cfg: CodeGenConfig): string {
  const { params, scale, ticksPerCombo = 30000, experimentLabel = "amisgc-experiment" } = cfg;
  return header(experimentLabel, "gpu") + `# Requirements: pip install torch
# Run: python ${experimentLabel.replace(/\s+/g, "_")}_gpu.py
# GPU: any CUDA-capable GPU. Falls back to CPU if no GPU available.

import torch
import json, time, sys

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ── Config ─────────────────────────────────────────────────────────────────────
N = ${scale}
TICKS = ${ticksPerCombo}
DTYPE = torch.float32
${Object.entries(params).map(([k, v]) => `${k} = ${JSON.stringify(v)}`).join("\n")}
PHI_MIN, PU_MIN, SC_MIN = 0.05, 0.10, 0.10
GATE_STREAK_TARGET = 1000

# ── State ──────────────────────────────────────────────────────────────────────
torch.manual_seed(42)
a = torch.rand(N, device=device, dtype=DTYPE)
y = torch.zeros(N, device=device, dtype=DTYPE)
h = torch.ones(N, device=device, dtype=DTYPE) * 0.5
a_slow = a.clone()
W = torch.normal(0, 1.0 / (N ** 0.5), (N, N), device=device, dtype=DTYPE)
W.fill_diagonal_(0)

gate_streak = 0
gate_opened = False
phi_log, pu_log, sc_log = [], [], []

@torch.no_grad()
def softmax_stable(x):
    return torch.softmax(x, dim=0)

@torch.no_grad()
def approx_phi(y_vec):
    active = (y_vec > 0.05).nonzero(as_tuple=True)[0]
    if active.numel() < 2:
        return 0.0
    idx = active[torch.randperm(active.numel())[:min(30, active.numel())]]
    pairs = y_vec[idx]
    phi = float(torch.pdist(pairs.unsqueeze(1)).mean())
    return phi

@torch.no_grad()
def approx_pu(y_vec, a_s):
    if y_vec.std() < 1e-8 or a_s.std() < 1e-8:
        return 0.0
    y_n = (y_vec - y_vec.mean()) / (y_vec.std() + 1e-8)
    a_n = (a_s - a_s.mean()) / (a_s.std() + 1e-8)
    return float((y_n * a_n).mean().clamp(0, 1))

@torch.no_grad()
def approx_sc(y_now, y_prev):
    n1, n2 = y_now.norm(), y_prev.norm()
    if n1 < 1e-8 or n2 < 1e-8:
        return 0.0
    return float((y_now * y_prev).sum() / (n1 * n2))

# ── Simulation ─────────────────────────────────────────────────────────────────
print(f"AMISGC GPU run | N={N} | ticks={TICKS} | device={device}")
y_prev = y.clone()
t_start = time.time()

for t in range(TICKS):
    C = softmax_stable(a)
    G = float(((C * a ** 2).sum() / ((C * a).sum() + 1e-8)).clamp(-4, 4))

    logits = (a + TAU_ATT * G) / max(TAU_ATT, 0.1)
    C = softmax_stable((a + GAMMA_GLOBAL * G) / TAU_ATT)

    lateral = W @ y
    h_new = (1 - DELTA_TEMPORAL) * h + DELTA_TEMPORAL * (C + GAMMA_GLOBAL * G + lateral)
    noise = torch.normal(0, NOISE_SIGMA, (N,), device=device, dtype=DTYPE)
    y_new = torch.relu(h_new + noise)

    entropy = -(C * (C + 1e-8).log()).sum().item()
    a = a + 0.01 * (C - a) + BETA_ENTROPY * entropy / (torch.log(torch.tensor(float(N))) + 1e-8) * 0.01
    a_slow = 0.98 * a_slow + 0.02 * a

    y_prev_copy = y.clone()
    h, y = h_new, y_new

    if t % 100 == 0:
        phi = approx_phi(y)
        pu = approx_pu(y, a_slow)
        sc = approx_sc(y, y_prev_copy)
        phi_log.append(phi)
        pu_log.append(pu)
        sc_log.append(sc)

        gate_open = phi > PHI_MIN and pu > PU_MIN and sc > SC_MIN
        gate_streak = gate_streak + 100 if gate_open else 0
        if gate_streak >= GATE_STREAK_TARGET:
            gate_opened = True

        if t % 5000 == 0:
            elapsed = time.time() - t_start
            status = "GATE OPEN" if gate_opened else f"NO-GO streak={gate_streak}"
            print(f"  t={t:6d} | Phi={phi:.4f} | PU={pu:.4f} | S_C={sc:.4f} | {status} | {elapsed:.1f}s")
            if device.type == "cuda":
                print(f"  GPU memory: {torch.cuda.memory_allocated() / 1e6:.1f} MB")

elapsed = time.time() - t_start
import numpy as np
result = {
    "gate_opened": gate_opened,
    "final_phi": phi_log[-1] if phi_log else 0,
    "final_pu": pu_log[-1] if pu_log else 0,
    "final_sc": sc_log[-1] if sc_log else 0,
    "mean_phi": float(np.mean(phi_log)) if phi_log else 0,
    "ticks_per_sec": TICKS / elapsed,
    "device": str(device),
}
print("\\n=== RESULT ===")
print(json.dumps(result, indent=2))
sys.exit(0 if gate_opened else 1)
`;
}

// ── Neuromorphic template (Norse / Loihi-compatible) ──────────────────────────

function generateNeuromorphic(cfg: CodeGenConfig): string {
  const { params, scale, ticksPerCombo = 30000, experimentLabel = "amisgc-experiment" } = cfg;
  return header(experimentLabel, "neuromorphic") + `# Requirements: pip install norse torch
# Norse: spiking neural network library with Loihi-compatible neuron models.
# Run on CPU for validation; deploy to Intel Loihi 2 for <1W power consumption.
# Loihi deployment: export via lava-nc (pip install lava-nc) — see README.

import torch
import norse.torch as snn
import json, time, sys

# ── Config ─────────────────────────────────────────────────────────────────────
N = ${scale}
TICKS = ${ticksPerCombo}
${Object.entries(params).map(([k, v]) => `${k} = ${JSON.stringify(v)}`).join("\n")}

# Biological plausibility targets
TARGET_SPARSITY = 0.04   # 4% active neurons (brain range: 2-6%)
TARGET_POWER_W  = 1.0    # < 1W for N=1M (brain: 20W for 86B neurons)
FLOPS_PER_NEURON_PER_TICK = 12  # attention(5) + integration(3) + plasticity(4)

# ── Spiking LIF neuron layer (Leaky Integrate-and-Fire) ───────────────────────
# Threshold tau_mem matches DELTA_TEMPORAL for biologically grounded timescale.
lif_params = snn.LIFParameters(
    tau_mem_inv=1.0 / max(DELTA_TEMPORAL, 0.1),
    tau_syn_inv=1.0 / max(TAU_ATT, 0.1),
    v_th=torch.tensor(0.5),
    v_reset=torch.tensor(0.0),
    method="super",   # SuperSpike surrogate gradient
)

# ── Network ────────────────────────────────────────────────────────────────────
torch.manual_seed(42)
W = torch.normal(0, 1.0 / (N ** 0.5), (N, N))
W.fill_diagonal_(0)
# Sparse connectivity (biological justification: local cortical columns)
mask = torch.bernoulli(torch.ones(N, N) * 0.1)  # 10% connectivity
W = W * mask

# LIF state
state = snn.LIFState(
    z=torch.zeros(N),
    v=torch.zeros(N),
    i=torch.zeros(N),
)

# Global attractor field (continuous)
a = torch.rand(N)
a_slow = a.clone()

phi_log, spike_rates = [], []
gate_streak, gate_opened = 0, False
t_start = time.time()

print(f"AMISGC Neuromorphic (Norse/LIF) | N={N} | ticks={TICKS}")
print(f"Biological targets: sparsity={TARGET_SPARSITY*100:.0f}%, power<{TARGET_POWER_W}W")

for t in range(TICKS):
    # Global field injection (continuous → discrete spike threshold)
    C = torch.softmax(a / TAU_ATT, dim=0)
    G = float(((C * a**2).sum() / ((C * a).sum() + 1e-8)).clamp(-4, 4))

    # Input current: global field + lateral (sparse) recurrent
    I_in = GAMMA_GLOBAL * G + (W @ state.z)

    # LIF step
    z_new, state = snn.lif_step(I_in, state, lif_params)

    # Slow apical EMA (top-down context signal)
    a_slow = 0.98 * a_slow + 0.02 * a
    a = a + 0.01 * (z_new.float() - a)

    if t % 100 == 0:
        sparsity = float(z_new.float().mean())
        spike_rates.append(sparsity)

        # Phi approximation from spike correlations
        active = (z_new > 0).nonzero(as_tuple=True)[0]
        phi = float(len(active)) / N  # proxy: fraction active (true IIT requires full partition)
        pu = max(0.0, float((z_new.float() * a_slow).mean() / (a_slow.std() + 1e-8)))
        sc = float((z_new.float() * a).sum() / (z_new.float().norm() * a.norm() + 1e-8))
        phi_log.append(phi)

        gate_streak = gate_streak + 100 if (phi > 0.04 and pu > 0.05) else 0
        if gate_streak >= 500:
            gate_opened = True

        if t % 5000 == 0:
            power_est_mW = N * FLOPS_PER_NEURON_PER_TICK * 1000 * 1e-9
            elapsed = time.time() - t_start
            print(f"  t={t:6d} | sparsity={sparsity:.3f} | Phi~={phi:.4f} | PU~={pu:.4f} | power~={power_est_mW:.3f}mW | {elapsed:.1f}s")

# ── Biological plausibility report ────────────────────────────────────────────
import numpy as np
mean_sparsity = float(np.mean(spike_rates)) if spike_rates else 0
power_at_1M_W = 1_000_000 * FLOPS_PER_NEURON_PER_TICK * 1000 * 1e-12
elapsed = time.time() - t_start

result = {
    "gate_opened": gate_opened,
    "mean_phi_proxy": float(np.mean(phi_log)) if phi_log else 0,
    "mean_sparsity": mean_sparsity,
    "sparsity_in_target": 0.02 <= mean_sparsity <= 0.06,
    "power_at_1M_neurons_W": power_at_1M_W,
    "power_plausible": power_at_1M_W < 1.0,
    "ticks_per_sec": TICKS / elapsed,
    "note": "Phi proxy = spike fraction; true IIT requires full partition sweep (offline).",
}
print("\\n=== BIOLOGICAL PLAUSIBILITY REPORT ===")
print(json.dumps(result, indent=2))
sys.exit(0)
`;
}

// ── Public API ─────────────────────────────────────────────────────────────────

export function generateCode(cfg: CodeGenConfig): CodeGenResult {
  const slug = (cfg.experimentLabel ?? "amisgc").replace(/\s+/g, "_").toLowerCase();

  switch (cfg.target) {
    case "cpu": {
      const filename = `${slug}_cpu.py`;
      return {
        target: "cpu",
        filename,
        language: "python",
        code: generateCPU(cfg),
        runInstructions: `pip install numpy\npython ${filename}`,
        estimatedSpeedup: "1x baseline (NumPy vectorised, ~200 ticks/sec for N=81)",
      };
    }
    case "gpu": {
      const filename = `${slug}_gpu.py`;
      return {
        target: "gpu",
        filename,
        language: "python",
        code: generateGPU(cfg),
        runInstructions: `pip install torch\npython ${filename}`,
        estimatedSpeedup: "10–100x vs CPU (CUDA parallelism). N=10 000+ feasible.",
      };
    }
    case "neuromorphic": {
      const filename = `${slug}_neuromorphic.py`;
      return {
        target: "neuromorphic",
        filename,
        language: "python",
        code: generateNeuromorphic(cfg),
        runInstructions: `pip install norse torch\npython ${filename}\n# Loihi deployment: pip install lava-nc && lava-run ${filename}`,
        estimatedSpeedup: "1000x+ on Loihi 2 with <1mW for N=1000. Brain-like energy budget.",
      };
    }
  }
}
